"""changed id in User

Revision ID: 173ba3b5226a
Revises: 3ebc6ce86722
Create Date: 2025-07-05 17:36:08.300523

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "173ba3b5226a"
down_revision: Union[str, Sequence[str], None] = "3ebc6ce86722"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
