"""article and archived_article added user_id

Revision ID: 772b53893493
Revises: 811397344b0c
Create Date: 2025-07-12 19:40:40.401646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "772b53893493"
down_revision: Union[str, Sequence[str], None] = "811397344b0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archived_articles", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "archived_articles", "users", ["user_id"], ["id"])
    op.add_column("articles", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "articles", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "articles", type_="foreignkey")
    op.drop_column("articles", "user_id")
    op.drop_constraint(None, "archived_articles", type_="foreignkey")
    op.drop_column("archived_articles", "user_id")
    # ### end Alembic commands ###
