"""users add is_active and accepted_at, article add is_delete

Revision ID: b99dd6e0d595
Revises: 6e4fb7ea72f3
Create Date: 2025-07-10 00:40:10.640830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b99dd6e0d595"
down_revision: Union[str, Sequence[str], None] = "6e4fb7ea72f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("is_delete", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "activated_at")
    op.drop_column("users", "is_active")
    op.drop_column("articles", "is_delete")
    # ### end Alembic commands ###
