"""change article and archived_articles

Revision ID: d7f87e2f7bb0
Revises: 6b8f738eeb3e
Create Date: 2025-07-11 15:56:54.115233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7f87e2f7bb0"
down_revision: Union[str, Sequence[str], None] = "6b8f738eeb3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_articles",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "archived_articles",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "archived_articles", sa.Column("category_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "archived_articles", "categories", ["category_id"], ["id"]
    )
    op.add_column(
        "articles",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "articles",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.drop_column("articles", "is_delete")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("is_delete", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("articles", "updated_at")
    op.drop_column("articles", "created_at")
    op.drop_constraint(None, "archived_articles", type_="foreignkey")
    op.drop_column("archived_articles", "category_id")
    op.drop_column("archived_articles", "updated_at")
    op.drop_column("archived_articles", "created_at")
    # ### end Alembic commands ###
